### ISSUE TITLE
Receiving flow

### ISSUE THREAD

**Issue by Jemesson** [aws-samples/aws-partner-custom-crm-connector#6]
Does it work properly on receiving opportunities from AWS to CRM, such as Salesforce?
Regards.

**Comment by frumania** [comment]
This solution only accelerates the **import** from a third party CRM to AWS APN, not the other direction.
For Salesforce however, you can use the official connector:
https://appexchange.salesforce.com/appxListingDetail?listingId=a0N4V00000IYf0nUAD&tab=e
